### ISSUE TITLE
关于“但无法使用核显加速”

### ISSUE THREAD

**Issue by zzymissyou** [dpdpzz/msi-b560i-hackintosh#1]
请问用什么测试核显加速？解码是指VDADecoderChecker测试通过。videoproc converter 4k 测试通过是么？那核显加速是如何测试呢 ？是不是用intel power gadget 观察GFX的频率啊？

**Comment by clhg** [comment]
1、请问用什么测试核显加速？那核显加速是如何测试呢 ？
你可以用FCPX导出视频看看。
2、解码是指VDADecoderChecker测试通过。videoproc converter 4k 测试通过是么？是不是用intel power gadget 观察GFX的频率啊？
是。
3、500系列无法加载Apple Guc Fireware。

**Comment by zzymissyou** [comment]
https://dortania.github.io/hackintosh/updates/2021/04/24/rocket-lake.html 此贴说CML IGPU works fine without connectors as a video decoding accelerator for Polaris. ，bilibili此贴up主在1楼说可以加速，https://www.bilibili.com/video/BV1aa411W7JX?spm_id_from=333.999.0.0&vd_source=7177a273fe6e2b56fa3c7d4d1ef3cf48，我有点疑惑了

**Comment by clhg** [comment]
关于你列举的例子:
1.我不知道英文资料所测试的平台是什么，确实有极少数的主板可以，但不是这一块。
2.B站视频的核显id并不是加速id。
